#!/usr/bin/env python3
"""Convert an AI-generated raw sprite sheet grid into a tiled sprite sheet bundle.

This script acts as the processor for image-to-image AI sprite generation.
It takes a grid image (e.g. 2x4 walk cycle generated by AI), splits it into frames,
removes the background using auto/white/magenta detection, and exports
the standard artifact bundle:
  source.png, raw-sheet.png, raw-sheet-clean.png, sheet-transparent.png,
  frame-1..N.png, animation.gif, pipeline-meta.json
"""

from __future__ import annotations

import argparse
import json
import math
import re
from collections import deque
from pathlib import Path

import numpy as np
from PIL import Image


def remove_bg_color(
    img: Image.Image,
    target_color: tuple[int, int, int],
    threshold: int = 30,
    edge_threshold: int | None = None,
) -> Image.Image:
    if edge_threshold is None:
        edge_threshold = int(threshold * 2.0)
    img = img.convert("RGBA")
    pixels = img.load()
    width, height = img.size
    tr, tg, tb = target_color

    def dist(r: int, g: int, b: int) -> float:
        return math.sqrt((r - tr) ** 2 + (g - tg) ** 2 + (b - tb) ** 2)

    # 初步掃描：將距離非常近的像素直接設為透明
    for x in range(width):
        for y in range(height):
            r, g, b, a = pixels[x, y]
            if a == 0:
                continue
            if dist(r, g, b) < threshold:
                pixels[x, y] = (0, 0, 0, 0)

    visited: set[tuple[int, int]] = set()
    queue: deque[tuple[int, int]] = deque()
    # 從邊界開始 Flood Fill
    for x in range(width):
        queue.append((x, 0))
        queue.append((x, height - 1))
    for y in range(height):
        queue.append((0, y))
        queue.append((width - 1, y))

    while queue:
        x, y = queue.popleft()
        if (x, y) in visited or not (0 <= x < width) or not (0 <= y < height):
            continue
        visited.add((x, y))
        r, g, b, a = pixels[x, y]
        
        if a == 0:
            # 透明像素繼續往內推
            for dx in (-1, 0, 1):
                for dy in (-1, 0, 1):
                    if dx == 0 and dy == 0: continue
                    nb = (x + dx, y + dy)
                    if nb not in visited:
                        queue.append(nb)
        else:
            d = dist(r, g, b)
            if d < edge_threshold:
                # Alpha Matting: 依據距離線性映射 Alpha (距離越近越透明)
                alpha_ratio = (d - threshold) / (edge_threshold - threshold)
                alpha_ratio = max(0.0, min(1.0, alpha_ratio))
                
                if alpha_ratio < 0.15: # 避免除以接近0的數值造成色彩爆炸
                    pixels[x, y] = (0, 0, 0, 0)
                else:
                    new_alpha = int(255 * alpha_ratio)
                    # Color Decontamination: 從混合色中扣除背景色，還原真實顏色
                    orig_r = min(255, max(0, int((r - tr * (1 - alpha_ratio)) / alpha_ratio)))
                    orig_g = min(255, max(0, int((g - tg * (1 - alpha_ratio)) / alpha_ratio)))
                    orig_b = min(255, max(0, int((b - tb * (1 - alpha_ratio)) / alpha_ratio)))
                    pixels[x, y] = (orig_r, orig_g, orig_b, new_alpha)
                
                # 邊緣像素仍可繼續往內推尋找其他邊緣
                for dx in (-1, 0, 1):
                    for dy in (-1, 0, 1):
                        if dx == 0 and dy == 0: continue
                        nb = (x + dx, y + dy)
                        if nb not in visited:
                            queue.append(nb)
                            
    # --- Defringe (Magenta Spill Suppression) ---
    # 如果背景色是紫紅色 (R, B 遠大於 G)，執行邊緣消光
    if tr > tg + 100 and tb > tg + 100:
        edge_pixels = []
        for i in range(width):
            for j in range(height):
                _, _, _, a_val = pixels[i, j]
                if a_val > 0:
                    is_edge = False
                    # 尋找 4 像素內的透明區域作為邊界判定
                    for dx in range(-4, 5):
                        for dy in range(-4, 5):
                            nx, ny = i + dx, j + dy
                            if 0 <= nx < width and 0 <= ny < height:
                                if pixels[nx, ny][3] == 0:
                                    is_edge = True
                                    break
                        if is_edge: break
                    if is_edge:
                        edge_pixels.append((i, j))
        
        for i, j in edge_pixels:
            pr, pg, pb, pa = pixels[i, j]
            # 如果該邊緣像素呈現紫紅色傾向
            if pr > pg + 5 and pb > pg + 5:
                # 採用標準的 Spill Suppression 演算法，保證 R 和 B 不超過 G
                new_pr = min(pr, pg)
                new_pb = min(pb, pg)
                pixels[i, j] = (new_pr, pg, new_pb, pa)
    # --------------------------------------------

    return img


def sample_bg_color(img: Image.Image, sample_radius: int = 5) -> tuple[int, int, int]:
    rgb = img.convert("RGB")
    w, h = rgb.size
    samples: list[tuple[int, int, int]] = []
    for x in range(min(sample_radius, w)):
        for y in range(min(sample_radius, h)):
            samples.append(rgb.getpixel((x, y)))
            samples.append(rgb.getpixel((w - 1 - x, y)))
            samples.append(rgb.getpixel((x, h - 1 - y)))
            samples.append(rgb.getpixel((w - 1 - x, h - 1 - y)))
    r_vals = sorted(s[0] for s in samples)
    g_vals = sorted(s[1] for s in samples)
    b_vals = sorted(s[2] for s in samples)
    mid = len(r_vals) // 2
    return (r_vals[mid], g_vals[mid], b_vals[mid])


def compose_sheet(frames: list[Image.Image], rows: int, cols: int, cell_size: int) -> Image.Image:
    canvas = Image.new("RGBA", (cols * cell_size, rows * cell_size), (0, 0, 0, 0))
    for index, frame in enumerate(frames):
        row, col = divmod(index, cols)
        canvas.paste(frame, (col * cell_size, row * cell_size), frame)
    return canvas


def compose_on_magenta(frames: list[Image.Image], rows: int, cols: int, cell_size: int) -> Image.Image:
    canvas = Image.new("RGB", (cols * cell_size, rows * cell_size), (255, 0, 255))
    for idx, frame in enumerate(frames):
        row, col = divmod(idx, cols)
        x, y = col * cell_size, row * cell_size
        if frame.mode == "RGBA":
            r, g, b, a = frame.split()
            rgb = Image.merge("RGB", (r, g, b))
            canvas.paste(rgb, (x, y), a)
        else:
            canvas.paste(frame.convert("RGB"), (x, y))
    return canvas


def save_transparent_gif(frames: list[Image.Image], out_path: Path, duration: int) -> None:
    if not frames:
        raise ValueError("No frames to encode.")

    key = (255, 0, 254)
    width, height = frames[0].size
    stacked = Image.new("RGB", (width, height * len(frames)), key)

    for index, frame in enumerate(frames):
        r, g, b, a = frame.split()
        hard_mask = a.point(lambda value: 255 if value >= 128 else 0)
        rgb = Image.merge("RGB", (r, g, b))
        stacked.paste(rgb, (0, index * height), hard_mask)

    paletted = stacked.convert("P", palette=Image.Palette.ADAPTIVE, colors=256, dither=Image.Dither.NONE)
    palette = list(paletted.getpalette() or [])
    while len(palette) < 256 * 3:
        palette.append(0)

    key_index = None
    for index in range(256):
        if palette[index * 3 : index * 3 + 3] == list(key):
            key_index = index
            break
    if key_index is None:
        best_distance = None
        best_index = 0
        for index in range(256):
            r, g, b = palette[index * 3], palette[index * 3 + 1], palette[index * 3 + 2]
            distance = (r - key[0]) ** 2 + (g - key[1]) ** 2 + (b - key[2]) ** 2
            if best_distance is None or distance < best_distance:
                best_distance = distance
                best_index = index
        key_index = best_index

    if key_index != 0:
        lut = np.arange(256, dtype=np.uint8)
        lut[0], lut[key_index] = key_index, 0
        arr = np.array(paletted)
        arr = lut[arr]
        paletted = Image.fromarray(arr, mode="P")
        for channel in range(3):
            zero_idx = channel
            key_idx = key_index * 3 + channel
            palette[zero_idx], palette[key_idx] = palette[key_idx], palette[zero_idx]
        paletted.putpalette(palette)

    out_frames = [
        paletted.crop((0, index * height, width, (index + 1) * height))
        for index in range(len(frames))
    ]
    out_frames[0].save(
        out_path,
        format="GIF",
        save_all=True,
        append_images=out_frames[1:],
        duration=duration,
        loop=0,
        disposal=2,
        transparency=0,
        background=0,
    )


def cmd_process(args: argparse.Namespace) -> None:
    out_dir: Path = args.output_dir
    out_dir.mkdir(parents=True, exist_ok=True)

    frames_count: int = args.frames
    cols: int = args.cols
    rows: int = math.ceil(frames_count / cols)

    # 1. Load source
    src = Image.open(args.input).convert("RGBA")
    src.save(out_dir / "source.png")

    src_w, src_h = src.size
    cell_w = src_w // cols
    cell_h = src_h // rows

    # 2. Determine background color globally
    bg_mode = args.bg_mode
    bg_color_used = None
    if bg_mode == "magenta":
        bg_color_used = (255, 0, 255)
    elif bg_mode == "white":
        bg_color_used = (255, 255, 255)
    elif bg_mode == "auto":
        bg_color_used = sample_bg_color(src)

    edge_threshold = args.bg_edge_threshold

    # rembg session (created once, reused for all frames)
    rembg_session = None
    rembg_remove = None
    if bg_mode == "rembg":
        print(f"Loading rembg model '{args.rembg_model}'...")
        try:
            from rembg import new_session
            from rembg import remove as rembg_remove
        except ImportError:
            raise SystemExit(
                "rembg is not installed.\n"
                'Run: pip install "rembg[cpu]"\n'
                'For GPU: pip install "rembg[gpu]"'
            )
        rembg_session = new_session(args.rembg_model)

    raw_frames = []
    cropped_frames = []

    # 3. Split grid and clean
    for row in range(rows):
        for col in range(cols):
            if len(cropped_frames) >= frames_count:
                break
            box = (col * cell_w, row * cell_h, (col + 1) * cell_w, (row + 1) * cell_h)
            cell_img = src.crop(box)
            
            trim = getattr(args, "trim_cell", 0)
            if trim > 0:
                cell_img = cell_img.crop((trim, trim, cell_w - trim, cell_h - trim))

            raw_frames.append(cell_img.copy())

            if bg_mode == "rembg":
                cleaned = rembg_remove(cell_img, session=rembg_session)
            elif bg_color_used:
                cleaned = remove_bg_color(cell_img, bg_color_used, args.bg_threshold, edge_threshold)
            else:
                cleaned = cell_img

            if getattr(args, "no_crop", False):
                pass
            else:
                bbox = cleaned.getbbox()
                if bbox:
                    cleaned = cleaned.crop(bbox)
            cropped_frames.append(cleaned)

    # Compose raw sheet
    compose_on_magenta(raw_frames, rows, cols, cell_w).save(out_dir / "raw-sheet.png")

    # 4. Compute shared scale if needed
    common_scale = None
    if args.shared_scale:
        max_width = max((f.size[0] for f in cropped_frames), default=0)
        max_height = max((f.size[1] for f in cropped_frames), default=0)
        if max_width > 0 and max_height > 0:
            common_scale = min(args.cell_size / max_width, args.cell_size / max_height) * args.fit_scale

    # 5. Fit to cell
    frames = []
    edge_touch = False
    for frame in cropped_frames:
        fw, fh = frame.size
        canvas = Image.new("RGBA", (args.cell_size, args.cell_size), (0, 0, 0, 0))
        if fw > 0 and fh > 0:
            scale = common_scale or (min(args.cell_size / fw, args.cell_size / fh) * args.fit_scale)
            new_w = max(1, int(fw * scale))
            new_h = max(1, int(fh * scale))
            resized = frame.resize((new_w, new_h), Image.Resampling.LANCZOS)
            paste_x = (args.cell_size - new_w) // 2
            if args.align in {"bottom", "feet"}:
                pad = max(0, int(args.cell_size * (1 - args.fit_scale) * 0.5))
                paste_y = args.cell_size - new_h - pad
            else:
                paste_y = (args.cell_size - new_h) // 2
            canvas.paste(resized, (paste_x, paste_y))

            if paste_x <= 2 or paste_y <= 2 or paste_x + new_w >= args.cell_size - 2 or paste_y + new_h >= args.cell_size - 2:
                edge_touch = True

        frames.append(canvas)

    # 6. Compose and save
    transparent_sheet = compose_sheet(frames, rows, cols, args.cell_size)
    transparent_sheet.save(out_dir / "raw-sheet-clean.png")
    transparent_sheet.save(out_dir / "sheet-transparent.png")

    for i, frame in enumerate(frames, start=1):
        frame.save(out_dir / f"frame-{i}.png")

    save_transparent_gif(frames, out_dir / "animation.gif", args.duration)

    artifacts = (
        ["source.png", "raw-sheet.png", "raw-sheet-clean.png", "sheet-transparent.png",
         "animation.gif", "pipeline-meta.json"]
        + [f"frame-{i}.png" for i in range(1, len(frames) + 1)]
    )

    meta = {
        "input": str(args.input.resolve()),
        "frames": len(frames),
        "cols": cols,
        "rows": rows,
        "duration": args.duration,
        "bg_mode": args.bg_mode,
        "bg_color_sampled": list(bg_color_used) if bg_color_used else None,
        "bg_threshold": args.bg_threshold,
        "rembg_model": args.rembg_model if args.bg_mode == "rembg" else None,
        "cell_size": args.cell_size,
        "fit_scale": args.fit_scale,
        "align": args.align,
        "shared_scale": args.shared_scale,
        "source_size": list(src.size),
        "edge_touch_frames": [1] if edge_touch else [],
        "output_dir": str(out_dir.resolve()),
        "artifacts": artifacts,
    }
    (out_dir / "pipeline-meta.json").write_text(json.dumps(meta, indent=2), encoding="utf-8")
    print(str(out_dir.resolve()))


def main() -> None:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--input", required=True, type=Path, help="Source image path")
    parser.add_argument("--output-dir", required=True, type=Path, help="Output directory")
    parser.add_argument("--frames", type=int, default=4, help="Total frame count")
    parser.add_argument("--cols", type=int, default=2, help="Grid columns (rows = ceil(frames/cols))")
    parser.add_argument("--duration", type=int, default=200, help="ms per frame")
    parser.add_argument(
        "--bg-mode",
        choices=["white", "magenta", "auto", "none", "rembg"],
        default="auto",
        help="Background removal mode",
    )
    parser.add_argument("--bg-threshold", type=int, default=30, help="Background color distance threshold")
    parser.add_argument("--bg-edge-threshold", type=int, default=None)
    parser.add_argument(
        "--rembg-model",
        type=str,
        default="isnet-anime",
        help=(
            "rembg model name. Only used with --bg-mode rembg. "
            "Options: isnet-anime, birefnet-general, u2net, u2net_human_seg. "
            "Default: isnet-anime"
        ),
    )
    parser.add_argument("--cell-size", type=int, default=128, help="Output cell size in px")
    parser.add_argument("--fit-scale", type=float, default=0.85, help="Sprite fill fraction of cell")
    parser.add_argument(
        "--align",
        choices=["center", "bottom", "feet"],
        default="center",
        help="Sprite alignment within cell",
    )
    parser.add_argument("--shared-scale", action="store_true", help="Use common scale across all frames")
    parser.add_argument("--no-crop", action="store_true", help="Disable bounding box cropping")
    parser.add_argument("--trim-cell", type=int, default=12, help="Trim N px from each cell edge")
    args = parser.parse_args()
    cmd_process(args)


if __name__ == "__main__":
    main()
